name: 'Execução Manual'
on: 
  workflow_dispatch

jobs:

  e2e-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando depêndencias
        run: yarn

      - name: Testes E2E (end-to-end)
        run: yarn cypress run
      
      - uses: actions/upload-artifact@v4
        with:
          name: relatorio-de-testes
          path: ./cypress-report
